theme: jekyll-theme-minimal
title: Carl Vitzthum
logo: /img/headshot.jpg
description: >
  <a href="https://github.com/carlvitzthum/carlvitzthum.github.io/raw/master/img/resume_12_5_19.pdf" target="_blank">Download My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/carlvitzthum/" target="_blank">View My LinkedIn Profile</a>
